<a href="https://colab.research.google.com/github/vanessa-oreza/python/blob/main/Pandas_Tratamiento_Manipulacion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROBLEMA DE NEGOCIO**


---

Se trata de un algoritmo capaz de analizar las características de una propiedad -como comodidades, tamaño, ocupación del espacio en un período determinado- y sugerir al anfitrión un precio a cobrar por tarifas diarias que garantice ganancias en momentos de alta demanda.

##**0. Entendiendo el Problema**


---

In [100]:
import pandas as pd

In [101]:
datos = pd.read_json('/content/datos_hosting.json')
datos.head()

                                      info_inmuebles
0  {'evaluacion_general': '10.0', 'experiencia_lo...
1  {'evaluacion_general': '10.0', 'experiencia_lo...
2  {'evaluacion_general': '10.0', 'experiencia_lo...
3  {'evaluacion_general': '10.0', 'experiencia_lo...
4  {'evaluacion_general': '10.0', 'experiencia_lo...

In [102]:
datos = pd.json_normalize(datos['info_inmuebles'])
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

## **1. Datos numéricos**

In [103]:
columnas=list(datos.columns)
columnas

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_baños',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

In [104]:
datos=datos.explode(columnas[3:])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [105]:
datos.reset_index(drop=True,inplace=True)
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [106]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [107]:
import numpy as np

In [108]:
datos['max_hospedes']=datos['max_hospedes'].astype(np.int64)

In [109]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [110]:
col_numericas=['cantidad_baños','cantidad_cuartos','cantidad_camas']

In [111]:
datos[col_numericas]=datos[col_numericas].astype(np.int64)

In [112]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [113]:
datos['evaluacion_general']=datos['evaluacion_general'].astype(np.float64)

In [114]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [115]:
datos['precio'].astype(np.float64)

ValueError: could not convert string to float: '$110.00'

Como tenemos un símbolo de moneda, no funciona el mismo método.

Números en strings

1. Remover caracteres y limpiar los datos

In [116]:
datos['precio']=datos['precio'].apply(lambda x: x.replace('$','').replace(',','').strip())

In [117]:
datos.head(3)

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.00

2. Convertir los datos a decimales

In [118]:
datos['precio']=datos['precio'].astype(np.float64)

In [119]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

Transformación de múltiples columnas: doble corchetes

1 columna se denomina serie

2 columnas o más se denomina data.frame

In [120]:
datos[['cuota_deposito','cuota_limpieza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

<ipython-input-120-126b0f61926c>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  datos[['cuota_deposito','cuota_limpieza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

     cuota_deposito cuota_limpieza
0                 0              0
1                 0              0
2                 0              0
3                 0          20.00
4                 0          15.00
...             ...            ...
3813        1000.00         178.00
3814              0          99.00
3815              0              0
3816        1000.00         150.00
3817         500.00              0

[3818 rows x 2 columns]

sale un warning de que es mejor usar .map

In [121]:
datos[['cuota_deposito','cuota_limpieza']].map(lambda x: x.replace('$','').replace(',','').strip())

     cuota_deposito cuota_limpieza
0                 0              0
1                 0              0
2                 0              0
3                 0          20.00
4                 0          15.00
...             ...            ...
3813        1000.00         178.00
3814              0          99.00
3815              0              0
3816        1000.00         150.00
3817         500.00              0

[3818 rows x 2 columns]

In [122]:
datos[['cuota_deposito','cuota_limpieza']]=datos[['cuota_deposito','cuota_limpieza']].map(lambda x: x.replace('$','').replace(',','').strip())

In [123]:
datos[['cuota_deposito','cuota_limpieza']]=datos[['cuota_deposito','cuota_limpieza']].astype(np.float64)

In [124]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   float64
 11  cuota_limpieza        3818 non-null   float64
 12  precio                3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

## **2. Datos de texto**

In [125]:
datos['descripcion_local']=datos['descripcion_local'].str.lower()

In [126]:
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,very lovely and cozy room for one. convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,the “studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [127]:
datos['descripcion_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [128]:
datos['descripcion_local']=datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [129]:
datos['descripcion_local'][3169]

"built  run and supported by seattle tech and start up veterans  grokhome's focus is to create a supportive environment for smart people working on interesting projects  start ups and more  this listing is an upper bunk  in a 2-person shared room   note  this fall  there will be major renovations happening on one kitchen and bathroom at a time  there will always be two other working kitchens and two working bathrooms in the house  we'll work to minimize the impact these renovations have on your stay    this listing is only available to those working in the tech science space  live in a hacker house  and immerse yourself in the seattle tech scene  you can expect to be surrounded by smart people solving big problems or working on something fun  we have frequent demo nights  and love when our guests share something they are passionate about  if you're new to the city  our deep ties to the seattle tech scene can help you get involved  expand your network  develop your ideas  and learn somet"

In [130]:
datos['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

0       this clean and comfortable one bedroom sits ri...
1       our century old upper queen anne house is loca...
2       cozy room in two-bedroom apartment along the l...
3       very lovely and cozy room for one  convenientl...
4       the  studio at mibbett hollow' is in a beautif...
                              ...
3813    beautiful craftsman home in the historic wedgw...
3814    located in a very easily accessible area of se...
3815    this home is fully furnished and available wee...
3816    this business-themed modern home features    h...
3817    this welcoming home is in the quiet residentia...
Name: descripcion_local, Length: 3818, dtype: object

In [131]:
datos['descripcion_local'].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one  convenientl...
4    the  studio at mibbett hollow' is in a beautif...
Name: descripcion_local, dtype: object

###**Tokenización**🗿

.split convierte la cadena de texto en lista de palabras o tokens!

In [132]:
datos['descripcion_local']=datos['descripcion_local'].str.split()

In [133]:
datos['comodidades'].str.replace('\{|}|"','',regex=True)

0       Internet,Wireless Internet,Kitchen,Free Parkin...
1       TV,Internet,Wireless Internet,Kitchen,Free Par...
2       TV,Internet,Wireless Internet,Kitchen,Free Par...
3       Internet,Wireless Internet,Kitchen,Free Parkin...
4       Wireless Internet,Kitchen,Free Parking on Prem...
                              ...
3813    TV,Cable TV,Internet,Wireless Internet,Air Con...
3814    TV,Cable TV,Internet,Wireless Internet,Kitchen...
3815    TV,Cable TV,Internet,Wireless Internet,Air Con...
3816    TV,Cable TV,Internet,Wireless Internet,Air Con...
3817    TV,Internet,Wireless Internet,Kitchen,Free Par...
Name: comodidades, Length: 3818, dtype: object

In [134]:
datos['comodidades']=datos['comodidades'].str.replace('\{|}|"','',regex=True)

In [135]:
datos['comodidades']=datos['comodidades'].str.split(',')

In [136]:
datos['comodidades']

0       [Internet, Wireless Internet, Kitchen, Free Pa...
1       [TV, Internet, Wireless Internet, Kitchen, Fre...
2       [TV, Internet, Wireless Internet, Kitchen, Fre...
3       [Internet, Wireless Internet, Kitchen, Free Pa...
4       [Wireless Internet, Kitchen, Free Parking on P...
                              ...
3813    [TV, Cable TV, Internet, Wireless Internet, Ai...
3814    [TV, Cable TV, Internet, Wireless Internet, Ki...
3815    [TV, Cable TV, Internet, Wireless Internet, Ai...
3816    [TV, Cable TV, Internet, Wireless Internet, Ai...
3817    [TV, Internet, Wireless Internet, Kitchen, Fre...
Name: comodidades, Length: 3818, dtype: object

In [137]:
datos['descripcion_vecindad']

0       Lower Queen Anne is near the Seattle Center (s...
1       Upper Queen Anne is a really pleasant, unique ...
2       The convenience of being in Seattle but on the...
3       Ballard is lovely, vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    Quiet, dead end street near I-5. The proximity...
3815                                                   --
3816    Your hosts made Madison Valley their home when...
3817    Despite the quiet, leafy streets of this resid...
Name: descripcion_vecindad, Length: 3818, dtype: object

In [138]:
datos['descripcion_vecindad']=datos['descripcion_vecindad'].str.lower()
datos['descripcion_vecindad']

0       lower queen anne is near the seattle center (s...
1       upper queen anne is a really pleasant, unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely, vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    quiet, dead end street near i-5. the proximity...
3815                                                   --
3816    your hosts made madison valley their home when...
3817    despite the quiet, leafy streets of this resid...
Name: descripcion_vecindad, Length: 3818, dtype: object

In [139]:
datos['descripcion_vecindad'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

0       lower queen anne is near the seattle center  s...
1       upper queen anne is a really pleasant  unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely  vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    quiet  dead end street near i-5  the proximity...
3815                                                   --
3816    your hosts made madison valley their home when...
3817    despite the quiet  leafy streets of this resid...
Name: descripcion_vecindad, Length: 3818, dtype: object

In [140]:
datos['descripcion_vecindad'][3816]

'your hosts made madison valley their home when settling in seattle 5 years ago... and haven\'t looked back since.   we love walking the streets of this neighborhood, and we will gladly suggest fun walks depending on your interests.  stroll to the beach at madison park.  walk by multi-million dollar estates.  discover hidden neighborhood gems such as the farmhouse with horses in the yard and the home that doubles as an eclectic art studio and antique truck gallery.  take a walk through the fabled arboretum to lake washington. once you have worked up your appetite, enjoy the countless restaurants that madison valley ("little paris") has to offer.  in addition to french gems, try our favorite tapas restaurant or the best japanese food east of tokyo.  take your morning coffee in one of numerous bakeries.  or opt for thai, pan-asian, craft pizza, tex-mex or more. our home provides easy access to downtown (pikes place market, seattle art museum, seattle great wheel), seattle center (space nee'

In [141]:
# Transformamos el texto en letras minúsculas
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.lower()
# Substituímos los caracteres especiales
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.replace('[^a-zA-Z0-9\-\']', ' ', regex=True)
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.replace('(?<!\w)-(?!\w)', '', regex=True)
# Transformamos el texto en lista, formando el token
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.split()
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...","[lower, queen, anne, is, near, the, seattle, c...",1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","[upper, queen, anne, is, a, really, pleasant, ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...","[the, convenience, of, being, in, seattle, but...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","[ballard, is, lovely, vibrant, and, one, of, t...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",[],1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

##**3. Datos de tiempo**

In [142]:
import datetime
# creando un objeto date con la fecha de hoy
hoy = datetime.date.today()

print("Fecha de hoy:", hoy)

Fecha de hoy: 2025-06-01

In [143]:
import datetime

# creando un objeto datetime con la fecha y hora actual
ahora = datetime.datetime.now()

print("Fecha y hora actual:", ahora)

Fecha y hora actual: 2025-06-01 00:23:42.411303

In [144]:
import datetime

# creando dos objetos date con fechas diferentes
data_1 = datetime.date(2001, 3, 3)
data_2 = datetime.date(2025, 3, 3)

# calculando la diferencia entre las dos fechas
diferencia = data_2 - data_1

print("Diferencia entre las dos fechas:", diferencia)

Diferencia entre las dos fechas: 8766 days, 0:00:00

In [145]:
data = pd.read_json('/content/inmuebles_disponibles.json')

In [146]:
data.head(3)

    id       fecha  lugar_disponible precio
0  857  2016-01-04             False   None
1  857  2016-01-05             False   None
2  857  2016-01-06             False   None

In [147]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  object
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [148]:
pd.to_datetime(data['fecha'])

0        2016-01-04
1        2016-01-05
2        2016-01-06
3        2016-01-07
4        2016-01-08
            ...
364995   2016-12-29
364996   2016-12-30
364997   2016-12-31
364998   2017-01-01
364999   2017-01-02
Name: fecha, Length: 365000, dtype: datetime64[ns]

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  object
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [150]:
data['fecha']=pd.to_datetime(data['fecha'])

In [151]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [152]:
data['fecha'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: fecha, Length: 365000, dtype: object

In [153]:
subset=data.groupby(data['fecha'].dt.strftime('%Y-%m'))['lugar_disponible'].sum()

In [154]:
data['precio'].fillna('0.0',inplace=True)

<ipython-input-154-2b38276ae712>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['precio'].fillna('0.0',inplace=True)

In [155]:
data['precio']=data['precio'].apply(lambda x: x.replace('$','').replace(',',''))

In [156]:
data['precio']=data['precio'].astype(np.float64)

In [157]:
data.sample(10)

          id      fecha  lugar_disponible  precio
244582  3551 2016-02-05              True    95.0
153410  2482 2016-04-23              True   159.0
230097   969 2016-05-30              True   115.0
312358  1146 2016-10-13              True   110.0
178523   745 2016-02-11             False     0.0
183393   442 2016-06-15              True   125.0
192897  3574 2016-06-29             False     0.0
336876  2314 2016-12-15              True    55.0
239546  1091 2016-04-19              True    75.0
308096  2135 2016-02-09              True   195.0

# **Desafíos**

**Trabajando en otros contextos**

Ha llegado el momento de poner en práctica todo lo aprendido durante las clases. Estos son proyectos adicionales para que los desarrollemos durante el curso, ¡para asegurarnos de que podamos practicar mucho! Para ello trabajaremos con 2 nuevos conjuntos de datos, pero esta vez serán mucho más pequeños. Las bases de datos son:

Proyecto Desafío 1: Ventas Online - dados_vendas_clientes.json;

Proyecto Desafío 2: Administración de Condominios - dados_locacao_imoveis.json.

##**Proyecto 1: Ventas Online**

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que más gastaron en productos durante los 5 días de ventas, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esta semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

La base de datos utilizada en este análisis es [dados_vendas_clientes.json](https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_vendas_clientes.json) y contiene información importante sobre los clientes, como el nombre registrado del cliente, el monto total pagado al momento de la compra y el día de la compra.

### Etapa 1

*Abrir la base de datos con Pandas y aplicar json_normalize.*

In [158]:
# Importar la biblioteca Pandas
import pandas as pd

In [159]:
# Leer el archivo json con read_json
d1 = pd.read_json('/content/dados_vendas_clientes.json')

In [160]:
d1.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [161]:
# Utilizar json_normalize
d1=pd.json_normalize(d1['dados_vendas'])

In [162]:
d1

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

### Etapa 2

*Eliminar datos en listas dentro del DataFrame;*

*Verificar tipos de datos;*

*Identificar columnas numéricas;*

*Transformar la columna numérica a tipo numérico.*

In [163]:
# Colectar los valores de las columnas y verificar
columnas = list(d1.columns)
columnas

['Data de venda', 'Cliente', 'Valor da compra']

In [164]:
# Deshacer las listas con explode
d1 = d1.explode(columnas[1:])
d1

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

In [165]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 1.2+ KB

In [166]:
d1['Valor da compra']=d1['Valor da compra'].apply(lambda x: x.replace('R$ ','').replace(',','.'))

In [167]:
d1['Valor da compra']=d1['Valor da compra'].astype(np.float64)

In [168]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.2+ KB

In [169]:
d1.sample(5)

  Data de venda             Cliente  Valor da compra
2    08/06/2022  Julya meireles 914           622.65
0    06/06/2022  DieGO ARMANDIU 210           573.33
3    09/06/2022     MaRIA Julia 444           759.16
1    07/06/2022  Isabely JOanes 738           168.07
2    08/06/2022    JOãO Gabriel 671           386.34

###Etapa 3

Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto resultó en una columna de nombres de clientes con una combinación de letras, mayúsculas y minúsculas, números y otros caracteres.

Sabiendo esto, manipula los textos de la columna Cliente para que el resultado sean los nombres de los clientes en letras minúsculas, con ausencia de caracteres especiales o números.

In [192]:
d1['Cliente']=d1['Cliente'].str.lower()
d1

  Data de venda             Cliente  Valor da compra
0    06/06/2022     @ana _lucia 321           836.50
0    06/06/2022  diego armandiu 210           573.33
0    06/06/2022  diego armandiu 210           392.80
0    06/06/2022  diego armandiu 210           512.34
1    07/06/2022  isabely joanes 738           825.31
1    07/06/2022  isabely joanes 738           168.07
1    07/06/2022  isabely joanes 738           339.18
1    07/06/2022  isabely joanes 738           314.69
2    08/06/2022  isabely joanes 738           682.05
2    08/06/2022    joão gabriel 671           386.34
2    08/06/2022  julya meireles 914           622.65
2    08/06/2022  julya meireles 914           630.79
3    09/06/2022  julya meireles 914           390.30
3    09/06/2022     maria julia 444           759.16
3    09/06/2022     maria julia 444           334.47
3    09/06/2022     maria julia 444           678.78
4    10/06/2022     maria julia 444           314.24
4    10/06/2022     pedro pasco 812           311.15
4    10/06/2022    paulo castro 481           899.16
4    10/06/2022   thiago fritzz 883           885.24

In [195]:
d1['Cliente']=d1['Cliente'].str.replace('[^a-z]',' ',regex=True)
d1

  Data de venda             Cliente  Valor da compra
0    06/06/2022      ana  lucia               836.50
0    06/06/2022  diego armandiu               573.33
0    06/06/2022  diego armandiu               392.80
0    06/06/2022  diego armandiu               512.34
1    07/06/2022  isabely joanes               825.31
1    07/06/2022  isabely joanes               168.07
1    07/06/2022  isabely joanes               339.18
1    07/06/2022  isabely joanes               314.69
2    08/06/2022  isabely joanes               682.05
2    08/06/2022    jo o gabriel               386.34
2    08/06/2022  julya meireles               622.65
2    08/06/2022  julya meireles               630.79
3    09/06/2022  julya meireles               390.30
3    09/06/2022     maria julia               759.16
3    09/06/2022     maria julia               334.47
3    09/06/2022     maria julia               678.78
4    10/06/2022     maria julia               314.24
4    10/06/2022     pedro pasco               311.15
4    10/06/2022    paulo castro               899.16
4    10/06/2022   thiago fritzz               885.24

###Etapa 4

En la columna Fecha de venta tenemos fechas en el formato 'día/mes/año' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualización de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

In [209]:
d1['Data de venda']

0    06/06/2022
0    06/06/2022
0    06/06/2022
0    06/06/2022
1    07/06/2022
1    07/06/2022
1    07/06/2022
1    07/06/2022
2    08/06/2022
2    08/06/2022
2    08/06/2022
2    08/06/2022
3    09/06/2022
3    09/06/2022
3    09/06/2022
3    09/06/2022
4    10/06/2022
4    10/06/2022
4    10/06/2022
4    10/06/2022
Name: Data de venda, dtype: object

In [211]:
import datetime

In [220]:
d1['Data de venda']=pd.to_datetime(d1['Data de venda'])
d1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 1.2+ KB

In [222]:
# Calcular el total recaudado en compras por cada cliente
total_compras = d1.groupby(['Cliente'])['Valor da compra'].sum()
# Visualizar el resultado
total_compras

Cliente
 ana  lucia            836.50
diego armandiu        1478.47
isabely joanes        2329.30
jo o gabriel           386.34
julya meireles        1643.74
maria julia           2086.65
paulo castro           899.16
pedro pasco            311.15
thiago fritzz          885.24
Name: Valor da compra, dtype: float64

##**Proyecto 2: Administración de condominios**

Administrar condominios es una tarea que requiere mucha atención y organización. Entre las diversas responsabilidades de gestión se encuentra el cobro del alquiler a los inquilinos. Para garantizar la buena salud financiera de la empresa, es fundamental que estos pagos se realicen de forma regular y puntual. Sin embargo, sabemos que esto no siempre sucede.

Teniendo esto en cuenta, propongo un desafío de procesamiento de datos con el objetivo de analizar el retraso en el pago del alquiler en el condominio de algunos residentes. Pongo a disposición la base de datos https://cdn3.gnarususercontent.com.br/2928-transformacao-manipulacao-dados/dados_locacao_imoveis.json, que contiene información sobre el departamento de los inquilinos, el día acordado para el pago del alquiler, el día en que se realiza el pago del alquiler y el monto del alquiler.

Analizar el retraso en el pago del alquiler en el condominio.

###Etapa 1

*Abrir la base de datos con Pandas y aplicar json_normalize.*

Primero, guardar el archivo en la computadora y subirlo al GoogleColab

In [170]:
d2=pd.read_json('/content/dados_locacao_imoveis.json')

In [171]:
d2

                                        dados_locacao
0   {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1   {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2   {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3   {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4   {'apartamento': 'C301 (blocoAP)', 'datas_combi...
5   {'apartamento': 'C302 (blocoAP)', 'datas_combi...
6   {'apartamento': 'D401 (blocoAP)', 'datas_combi...
7   {'apartamento': 'D402 (blocoAP)', 'datas_combi...
8   {'apartamento': 'E501 (blocoAP)', 'datas_combi...
9   {'apartamento': 'E502 (blocoAP)', 'datas_combi...
10  {'apartamento': 'F601 (blocoAP)', 'datas_combi...
11  {'apartamento': 'F602 (blocoAP)', 'datas_combi...
12  {'apartamento': 'G701 (blocoAP)', 'datas_combi...
13  {'apartamento': 'G702 (blocoAP)', 'datas_combi...
14  {'apartamento': 'H801 (blocoAP)', 'datas_combi...

In [172]:
d2=pd.json_normalize(d2['dados_locacao'])

In [173]:
d2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

### Etapa 2

*Eliminar datos en listas dentro del DataFrame;*

*Verificar tipos de datos;*

*Identificar columnas numéricas;*

*Transformar la columna numérica a tipo numérico.*

In [174]:
#Variable con las columnas
columns=list(d2.columns)
columns

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [175]:
#Deshacer las listas con explode
d2.explode(columns[1:])

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [176]:
#Como sí funcionó, realizamos el cambio en la variable

In [177]:
d2=d2.explode(columns[1:])

In [178]:
#Reestablecer el índice
d2.reset_index(drop=True,inplace=True)

In [179]:
d2.head(3)

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"

In [186]:
d2['valor_aluguel']=d2['valor_aluguel'].apply(lambda x: x.replace('$ ','').replace(" reais","").replace(",",''))

In [187]:
d2['valor_aluguel'].astype(np.float64)

0     10000.0
1     25000.0
2     11000.0
3     26000.0
4     12000.0
5     27000.0
6     13000.0
7     28000.0
8     14000.0
9     29000.0
10    15000.0
11    12000.0
12    16000.0
13    13000.0
14    17000.0
15    14000.0
16    18000.0
17    15000.0
18    19000.0
19    16000.0
20    20000.0
21    10000.0
22    21000.0
23    11000.0
24    22000.0
25    12000.0
26    23000.0
27    21000.0
28    24000.0
29    22000.0
Name: valor_aluguel, dtype: float64

###Etapa 3

Buscando explicar la organización de la identificación de los apartamentos, durante la creación del conjunto de datos se añadió el texto (blocoAP). Este texto informa que los nombres de los apartamentos están organizados con la letra mayúscula seguida del número del apartamento. Sin embargo, esto no aporta ninguna información a nuestros datos, por lo que resulta interesante eliminar este texto del conjunto de datos.

Con esto, manipule los textos de la columna apartamento para eliminar el texto (blocoAP) del DataFrame.

In [197]:
d2.sample(10)

       apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
5   B201 (blocoAP)                 03/07/2022         03/07/2022         27000
20  F601 (blocoAP)                 11/06/2022         17/06/2022         20000
17  E501 (blocoAP)                 09/07/2022         09/07/2022         15000
2   A102 (blocoAP)                 02/06/2022         02/06/2022         11000
9   C301 (blocoAP)                 05/07/2022         09/07/2022         29000
28  H801 (blocoAP)                 15/06/2022         18/06/2022         24000
7   B202 (blocoAP)                 04/07/2022         05/07/2022         28000
15  D402 (blocoAP)                 08/07/2022         14/07/2022         14000
0   A101 (blocoAP)                 01/06/2022         05/06/2022         10000
6   B202 (blocoAP)                 04/06/2022         07/06/2022         13000

In [198]:
d2['apartamento'].str.replace(' (blocoAP)',"")

0     A101
1     A101
2     A102
3     A102
4     B201
5     B201
6     B202
7     B202
8     C301
9     C301
10    C302
11    C302
12    D401
13    D401
14    D402
15    D402
16    E501
17    E501
18    E502
19    E502
20    F601
21    F601
22    F602
23    F602
24    G701
25    G701
26    G702
27    G702
28    H801
29    H801
Name: apartamento, dtype: object

In [199]:
d2['apartamento']=d2['apartamento'].str.replace(' (blocoAP)',"")

###Etapa 4

En las columnas datas_de_pagamento y datas_combinadas_pagamento tenemos fechas en el formato 'día/mes/año' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualización de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

Analizar el retraso en el pago de la renta en el condominio ficticio de algunos residentes.

In [223]:
d2.sample(4)

   apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
8         C301                 05/06/2022         10/06/2022         14000
10        C302                 06/06/2022         08/06/2022         15000
17        E501                 09/07/2022         09/07/2022         15000
26        G702                 14/06/2022         15/06/2022         23000

In [224]:
import datetime

In [232]:
# Transformar para el tipo datetime definiendo el formato de fecha como DD/MM/AAAA ('%d/%m/%Y')
d2['datas_combinadas_pagamento'] = pd.to_datetime(d2['datas_combinadas_pagamento'], format='%d/%m/%Y')
d2['datas_de_pagamento'] = pd.to_datetime(d2['datas_de_pagamento'], format='%d/%m/%Y')

In [233]:
d2

   apartamento datas_combinadas_pagamento datas_de_pagamento valor_aluguel
0         A101                 2022-06-01         2022-06-05         10000
1         A101                 2022-07-01         2022-07-03         25000
2         A102                 2022-06-02         2022-06-02         11000
3         A102                 2022-07-02         2022-07-06         26000
4         B201                 2022-06-03         2022-06-07         12000
5         B201                 2022-07-03         2022-07-03         27000
6         B202                 2022-06-04         2022-06-07         13000
7         B202                 2022-07-04         2022-07-05         28000
8         C301                 2022-06-05         2022-06-10         14000
9         C301                 2022-07-05         2022-07-09         29000
10        C302                 2022-06-06         2022-06-08         15000
11        C302                 2022-07-06         2022-07-12         12000
12        D401                 2022-06-07         2022-06-07         16000
13        D401                 2022-07-07         2022-07-09         13000
14        D402                 2022-06-08         2022-06-10         17000
15        D402                 2022-07-08         2022-07-14         14000
16        E501                 2022-06-09         2022-06-10         18000
17        E501                 2022-07-09         2022-07-09         15000
18        E502                 2022-06-10         2022-06-16         19000
19        E502                 2022-07-10         2022-07-12         16000
20        F601                 2022-06-11         2022-06-17         20000
21        F601                 2022-07-11         2022-07-13         10000
22        F602                 2022-06-12         2022-06-15         21000
23        F602                 2022-07-12         2022-07-12         11000
24        G701                 2022-06-13         2022-06-19         22000
25        G701                 2022-07-13         2022-07-20         12000
26        G702                 2022-06-14         2022-06-15         23000
27        G702                 2022-07-14         2022-07-17         21000
28        H801                 2022-06-15         2022-06-18         24000
29        H801                 2022-07-15         2022-07-16         22000

In [236]:
# Para contribuir en la solución del contexto es posible calcular la diferencia de días
# entre la fecha combinada y la fecha de pagamento con dt.days
d2['atraso'] = (d2['datas_de_pagamento'] - d2['datas_combinadas_pagamento']).dt.days
d2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso
0,A101,2022-06-01,2022-06-05,10000,4
1,A101,2022-07-01,2022-07-03,25000,2
2,A102,2022-06-02,2022-06-02,11000,0
3,A102,2022-07-02,2022-07-06,26000,4
4,B201,2022-06-03,2022-06-07,12000,4
5,B201,2022-07-03,2022-07-03,27000,0
6,B202,2022-06-04,2022-06-07,13000,3
7,B202,2022-07-04,2022-07-05,28000,1
8,C301,2022-06-05,2022-06-10,14000,5
9,C301,2022-07-05,2022-07-09,29000,4
10,C302,2022-06-06,2022-06-08,15000,2
11,C302,2022-07-06,2022-07-12,12000,6
12,D401,2022-06-07,2022-06-07,16000,0
13,D401,2022-07-07,2022-07-09,13000,2
14,D402,2022-06-08,2022-06-10,17000,2
15,D402,2022-07-08,2022-07-14,14000,6
16,E501,2022-06-09,2022-06-10,18000,1
17,E501,2022-07-09,2022-07-09,15000,0
18,E502,2022-06-10,2022-06-16,19000,6
19,E502,2022-07-10,2022-07-12,16000,2
20,F601,2022-06-11,2022-06-17,20000,6
21,F601,2022-07-11,2022-07-13,10000,2
22,F602,2022-06-12,2022-06-15,21000,3
23,F602,2022-07-12,2022-07-12,11000,0
24,G701,2022-06-13,2022-06-19,22000,6
25,G701,2022-07-13,2022-07-20,12000,7
26,G702,2022-06-14,2022-06-15,23000,1
27,G702,2022-07-14,2022-07-17,21000,3
28,H801,2022-06-15,2022-06-18,24000,3
29,H801,2022-07-15,2022-07-16,22000,1

In [239]:
# Calcular el promedio de tiempo de atraso por apartamentos
media_atraso = d2.groupby(['apartamento'])['atraso'].mean()
media_atraso

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: atraso, dtype: float64

¡Finito!✨🎉